version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: git config
          command: |
            git config --global user.email "istaka12@gmail.com"
            git config --global user.name "ganezasan"
      - run:
          name: push another branch
          command: |
            git checkout develop
            git commit --allow-empty -m '[ci skip] test'
            git push origin develop
workflows:
  version: 2
  app:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main            
